
server:
  port: 38300
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tw0713?useSSL=false&serverTimeZone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  level:
    root: info

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:com/talkweb/**/sql/*Mapper.xml

spring:
#  cloud:
#    sentinel:
#      transport:
#        dashboard: localhost:8080
  application:
    name: shop-goods-server


